import { useState, useRef } from "react";
import { useAdminTheme } from "../../context/AdminThemeContext";
import { Btn } from "../../components/ui";
import { inputSt, smallBtn } from "../../components/ui-helpers";
import { writeBatch, doc } from "firebase/firestore";
import { db } from "../../config/firebase";

export function CategoriesManager({ categories, menu, dbOps, showToast, isMobile }) {const{T:C,TF:F}=useAdminTheme();
  const [newName,setNewName]=useState("");const [editingId,setEditingId]=useState(null);const [editName,setEditName]=useState("");const [saving,setSaving]=useState(false);const inputRef=useRef(null);
  const [dragIdx,setDragIdx]=useState(null);const [overIdx,setOverIdx]=useState(null);const dragNodeRef=useRef(null);const [reordering,setReordering]=useState(false);
  async function handleAdd(){const name=newName.trim();if(!name)return;if(categories.find(c=>c.name.toLowerCase()===name.toLowerCase())){showToast("That category already exists","error");return;}setSaving(true);try{await dbOps.addCategory(name);setNewName("");showToast('"'+name+'" category added');inputRef.current?.focus();}catch(e){console.error(e);showToast("Add failed","error");}finally{setSaving(false);}}
  async function handleRename(id){const name=editName.trim();if(!name)return;if(categories.find(c=>c.name.toLowerCase()===name.toLowerCase()&&c.id!==id)){showToast("That name is already taken","error");return;}setSaving(true);try{await dbOps.renameCategory(id,name);setEditingId(null);showToast("Category renamed");}catch(e){console.error(e);showToast("Rename failed","error");}finally{setSaving(false);}}
  async function handleDelete(cat){const inUse=menu.filter(i=>i.category===cat.name).length;if(inUse>0){try{const fallbackCategory=categories.find(c=>c.name==="Other")?"Other":(categories.find(c=>c.id!==cat.id)?.name||"Other");const batch=writeBatch(db);menu.filter(i=>i.category===cat.name).forEach(item=>{batch.update(doc(db,"kioskMenu",item.id),{category:fallbackCategory});});batch.delete(doc(db,"kioskCategories",cat.id));await batch.commit();showToast('"'+cat.name+'" deleted \u2014 '+inUse+' item'+(inUse!==1?"s":"")+" moved to "+fallbackCategory);}catch(e){console.error(e);showToast("Delete failed","error");}}else{try{await dbOps.deleteCategory(cat.id);showToast('"'+cat.name+'" removed',"error");}catch(e){console.error(e);showToast("Delete failed","error");}}}
  function handleDragStart(e,idx){setDragIdx(idx);dragNodeRef.current=e.target.closest("[data-cat-row]");e.dataTransfer.effectAllowed="move";setTimeout(()=>{if(dragNodeRef.current)dragNodeRef.current.style.opacity="0.35";},0);}
  function handleDragOver(e,idx){e.preventDefault();e.dataTransfer.dropEffect="move";if(idx!==overIdx)setOverIdx(idx);}
  function handleDragEnd(){if(dragNodeRef.current)dragNodeRef.current.style.opacity="1";setDragIdx(null);setOverIdx(null);dragNodeRef.current=null;}
  async function handleDrop(e,dropIdx){e.preventDefault();if(dragIdx===null||dragIdx===dropIdx){handleDragEnd();return;}setReordering(true);try{const reordered=[...categories];const [moved]=reordered.splice(dragIdx,1);reordered.splice(dropIdx,0,moved);const batch=writeBatch(db);reordered.forEach((cat,i)=>{if(cat.sortOrder!==i)batch.update(doc(db,"kioskCategories",cat.id),{sortOrder:i});});await batch.commit();showToast("Categories reordered");}catch(e2){console.error(e2);showToast("Reorder failed","error");}finally{setReordering(false);handleDragEnd();}}
  return (
    <div style={{animation:"fadeUp .3s ease",maxWidth:580}}>
      <div style={{background:C.card,border:"1px solid "+C.border,borderRadius:14,padding:"18px 20px",marginBottom:18}}>
        <div style={{fontSize:12,letterSpacing:2,textTransform:"uppercase",color:C.muted,marginBottom:12}}>Add New Category</div>
        <div style={{display:"flex",gap:10}}><input ref={inputRef} value={newName} onChange={e=>setNewName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&handleAdd()} placeholder="e.g. BBQ, Spices, Seafood…" style={{...inputSt(false,C),flex:1}}/><Btn t={C} primary onClick={handleAdd} disabled={!newName.trim()||saving}>{saving?"Adding\u2026":"+ Add"}</Btn></div>
      </div>
      <div style={{background:C.card,border:"1px solid "+C.border,borderRadius:14,overflow:"hidden"}}>
        <div style={{display:"grid",gridTemplateColumns:isMobile?"1fr 60px 90px":"44px 1fr 80px 110px",borderBottom:"1px solid "+C.border,padding:"9px 18px"}}>{(isMobile?["Category Name","Items","Actions"]:["","Category Name","Items","Actions"]).map(h=><div key={h||"drag"} style={{fontSize:10,letterSpacing:2,textTransform:"uppercase",color:C.muted}}>{h}</div>)}</div>
        {categories.length===0?<div style={{padding:"40px",textAlign:"center",color:C.muted}}>No categories yet</div>:categories.map((cat,idx)=>{const itemCount=menu.filter(i=>i.category===cat.name).length;const isEditing=editingId===cat.id;return(
          <div key={cat.id} data-cat-row className="row-hover" draggable={!isMobile&&!isEditing} onDragStart={e=>!isMobile&&!isEditing&&handleDragStart(e,idx)} onDragOver={e=>!isMobile&&!isEditing&&handleDragOver(e,idx)} onDrop={e=>!isMobile&&handleDrop(e,idx)} onDragEnd={handleDragEnd} style={{display:"grid",gridTemplateColumns:isMobile?"1fr 60px 90px":"44px 1fr 80px 110px",borderBottom:"1px solid "+C.border,padding:"11px 18px",alignItems:"center",transition:"background .15s",background:overIdx===idx&&dragIdx!==idx?"rgba(155,28,28,.15)":"transparent",borderTop:overIdx===idx&&dragIdx!==idx?"2px solid "+C.red:"2px solid transparent",opacity:reordering?.5:1}}>
            {!isMobile&&<div style={{display:"flex",alignItems:"center",justifyContent:"center",cursor:isEditing?"default":"grab",userSelect:"none"}}><span style={{display:"flex",flexDirection:"column",alignItems:"center",gap:1,color:reordering?C.border:C.muted}} title="Drag to reorder"><span style={{fontSize:8,lineHeight:1}}>{"\u25B4"}</span><span style={{fontSize:16,lineHeight:.85,letterSpacing:0}}>{"\u2261"}</span><span style={{fontSize:8,lineHeight:1}}>{"\u25BE"}</span></span></div>}
            <div>{isEditing?<div style={{display:"flex",gap:8}}><input value={editName} onChange={e=>setEditName(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")handleRename(cat.id);if(e.key==="Escape")setEditingId(null);}} autoFocus style={{...inputSt(false,C),padding:"6px 10px",fontSize:14}}/><button onClick={()=>handleRename(cat.id)} disabled={!editName.trim()||saving} style={{background:C.green,border:"none",color:C.greenText,borderRadius:7,padding:"5px 12px",cursor:"pointer",fontSize:13,fontWeight:700}}>{"\u2713"}</button><button onClick={()=>setEditingId(null)} style={{background:C.border,border:"none",color:C.muted,borderRadius:7,padding:"5px 10px",cursor:"pointer",fontSize:13}}>{"\u2715"}</button></div>:<span style={{fontSize:15,color:C.cream,fontWeight:600}}>{cat.name}</span>}</div>
            <div><span style={{fontSize:13,color:itemCount>0?C.mutedLight:C.border}}>{itemCount} item{itemCount!==1?"s":""}</span></div>
            <div style={{display:"flex",gap:6}}>{!isEditing&&<><button onClick={()=>{setEditingId(cat.id);setEditName(cat.name);}} style={smallBtn(false,false,C)}>Rename</button><button onClick={()=>handleDelete(cat)} style={smallBtn(true,false,C)}>Del{itemCount>0?" ("+itemCount+")":""}</button></>}</div>
          </div>);})}
      </div>
    </div>
  );
}
