import { useState, useRef, useEffect } from "react";
import { useAdminTheme } from "../../context/AdminThemeContext";
import { Modal, ConfirmModal, Field, Btn } from "../../components/ui";
import { inputSt, smallBtn } from "../../components/ui-helpers";
import { Img } from "../../components/Img";
import { getStorage, ref, uploadBytes, getDownloadURL } from "firebase/storage";

const storage = getStorage();

function useWindowSize(){const [s,set]=useState({w:typeof window!=="undefined"?window.innerWidth:1200,h:typeof window!=="undefined"?window.innerHeight:800});useEffect(()=>{const h=()=>set({w:window.innerWidth,h:window.innerHeight});window.addEventListener("resize",h);return()=>window.removeEventListener("resize",h);},[]);return s;}

export function MenuManager({ menu, catNames, dbOps, showToast, isMobile }) {const{T:C,TF:F}=useAdminTheme();
  const blank={name:"",description:"",price:"",category:catNames[0]||"Other",image:"",isBundle:false,bundleItems:[],showOnKiosk:true,stock:"",inStock:true};
  const [editing,setEditing]=useState(null);const [isNew,setIsNew]=useState(false);const [search,setSearch]=useState("");const [filter,setFilter]=useState("All");const [viewFilter,setViewFilter]=useState("all");const [confirmDel,setConfirmDel]=useState(null);const [saving,setSaving]=useState({});const [dragIdx,setDragIdx]=useState(null);const [overIdx,setOverIdx]=useState(null);const dragNodeRef=useRef(null);
  const [selectMode,setSelectMode]=useState(false);const [selected,setSelected]=useState(new Set());const [confirmBulkDel,setConfirmBulkDel]=useState(false);
  const onCount=menu.filter(i=>i.showOnKiosk!==false).length;const offCount=menu.length-onCount;
  const onMenuSorted=menu.filter(i=>i.showOnKiosk!==false).sort((a,b)=>(a.menuOrder??999)-(b.menuOrder??999));
  const displayed=menu.filter(i=>{const matchCat=filter==="All"||i.category===filter;const matchSearch=i.name.toLowerCase().includes(search.toLowerCase());const matchView=viewFilter==="all"||(viewFilter==="on"&&i.showOnKiosk!==false)||(viewFilter==="off"&&i.showOnKiosk===false);return matchCat&&matchSearch&&matchView;}).sort((a,b)=>{const aOn=a.showOnKiosk!==false?0:1;const bOn=b.showOnKiosk!==false?0:1;if(aOn!==bOn)return aOn-bOn;return(a.menuOrder??999)-(b.menuOrder??999);});
  async function saveItem(item){if(saving._save)return;setSaving(prev=>({...prev,_save:true}));try{const isQB=!!item.qbItemId;const data=isQB?{description:item.description||"",category:item.category,image:item.image||"",showOnKiosk:item.showOnKiosk!==false,menuOrder:item.menuOrder??999,barcodeImage:item.barcodeImage||"",isBundle:!!item.isBundle,bundleItems:item.isBundle?(item.bundleItems||[]).filter(b=>b.itemId&&b.quantity>0&&menu.some(m=>m.id===b.itemId)):[]}:{name:item.name.trim(),description:item.description||"",price:parseFloat(item.price)||0,category:item.category,image:item.image||"",isBundle:!!item.isBundle,bundleItems:item.isBundle?(item.bundleItems||[]).filter(b=>b.itemId&&b.quantity>0&&menu.some(m=>m.id===b.itemId)):[],showOnKiosk:item.showOnKiosk!==false,menuOrder:item.menuOrder??999,sku:item.sku||"",barcodeImage:item.barcodeImage||"",stock:item.stock===""?null:parseInt(item.stock)||0,inStock:item.stock===""?true:(parseInt(item.stock)||0)>0};if(isNew){await dbOps.addMenuItem(data);showToast("Item added");}else{await dbOps.updateMenuItem(item.id,data);showToast("Item updated");}setEditing(null);}catch(e){console.error(e);showToast("Save failed","error");}finally{setSaving(prev=>{const n={...prev};delete n._save;return n;});}}
  async function deleteItem(id){try{await dbOps.deleteMenuItem(id);showToast("Item removed","error");setConfirmDel(null);}catch(e){console.error(e);showToast("Delete failed","error");}}
  async function toggleKiosk(item){const newVal=item.showOnKiosk===false;setSaving(prev=>({...prev,[item.id]:true}));try{await dbOps.updateMenuItem(item.id,{showOnKiosk:newVal});showToast(item.name+(newVal?" added to":" removed from")+" kiosk");}catch(e){console.error(e);showToast("Update failed","error");}finally{setSaving(prev=>{const n={...prev};delete n[item.id];return n;});}}
  function handleDragStart(e,idx){setDragIdx(idx);dragNodeRef.current=e.target.closest("[data-row]");e.dataTransfer.effectAllowed="move";setTimeout(()=>{if(dragNodeRef.current)dragNodeRef.current.style.opacity="0.35";},0);}
  function handleDragOver(e,idx){e.preventDefault();e.dataTransfer.dropEffect="move";if(idx!==overIdx)setOverIdx(idx);}
  async function handleDrop(e,dropIdx){e.preventDefault();if(dragIdx===null||dragIdx===dropIdx){setDragIdx(null);setOverIdx(null);return;}const dragItem=onMenuSorted[dragIdx];if(!dragItem)return;const reordered=[...onMenuSorted];const [moved]=reordered.splice(dragIdx,1);reordered.splice(dropIdx,0,moved);const updates=reordered.map((item,i)=>({id:item.id,menuOrder:i})).filter((u,i)=>reordered[i].menuOrder!==i);if(updates.length===0){setDragIdx(null);setOverIdx(null);return;}const ids=updates.map(u=>u.id);setSaving(prev=>{const n={...prev};ids.forEach(id=>{n[id]=true;});return n;});try{await Promise.all(updates.map(u=>dbOps.updateMenuItem(u.id,{menuOrder:u.menuOrder})));}catch(e2){console.error(e2);showToast("Reorder failed","error");}finally{setSaving(prev=>{const n={...prev};ids.forEach(id=>{delete n[id];});return n;});}setDragIdx(null);setOverIdx(null);}
  function handleDragEnd(){if(dragNodeRef.current)dragNodeRef.current.style.opacity="1";setDragIdx(null);setOverIdx(null);dragNodeRef.current=null;}
  function toggleSelect(id){setSelected(prev=>{const next=new Set(prev);if(next.has(id))next.delete(id);else next.add(id);return next;});}
  function toggleSelectAll(){const visibleIds=displayed.map(i=>i.id);const allSelected=visibleIds.length>0&&visibleIds.every(id=>selected.has(id));if(allSelected){setSelected(prev=>{const next=new Set(prev);visibleIds.forEach(id=>next.delete(id));return next;});}else{setSelected(prev=>{const next=new Set(prev);visibleIds.forEach(id=>next.add(id));return next;});}}
  async function deleteSelected(){if(selected.size===0)return;setSaving(prev=>({...prev,_bulk:true}));try{for(const id of selected){await dbOps.deleteMenuItem(id);}showToast(selected.size+" item"+(selected.size!==1?"s":"")+" deleted","error");setSelected(new Set());}catch(e){console.error(e);showToast("Delete failed","error");}finally{setSaving(prev=>{const n={...prev};delete n._bulk;return n;});}}
  return (
    <div style={{animation:"fadeUp .3s ease"}}>
      <div style={{display:"grid",gridTemplateColumns:isMobile?"1fr 1fr 1fr":"repeat(3,1fr)",gap:isMobile?8:12,marginBottom:20}}>
        {[{label:"Total Items",value:menu.length,color:C.cream},{label:"On Kiosk",value:onCount,color:C.greenText},{label:"Hidden",value:offCount,color:C.muted}].map(s=><div key={s.label} style={{background:C.card,border:"1px solid "+C.border,borderRadius:12,padding:"14px 16px"}}><div style={{fontSize:10,letterSpacing:2,textTransform:"uppercase",color:C.muted,marginBottom:8}}>{s.label}</div><div style={{fontFamily:F.display,fontSize:26,fontWeight:900,color:s.color}}>{s.value}</div></div>)}
      </div>
      <div style={{display:"flex",gap:10,marginBottom:16,flexWrap:"wrap",alignItems:"center"}}>
        <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search items…" style={{...inputSt(false,C),flex:1,minWidth:180}}/>
        <select value={filter} onChange={e=>setFilter(e.target.value)} style={inputSt(true,C)}><option value="All">All Categories</option>{catNames.map(c=><option key={c} value={c}>{c}</option>)}</select>
        <div style={{display:"flex",gap:4,background:C.card,border:"1px solid "+C.border,borderRadius:10,padding:3}}>{[{id:"all",label:"All ("+menu.length+")"},{id:"on",label:"On ("+onCount+")"},{id:"off",label:"Off ("+offCount+")"}].map(f=><button key={f.id} onClick={()=>setViewFilter(f.id)} style={{background:viewFilter===f.id?C.surface:"transparent",border:"1px solid "+(viewFilter===f.id?C.borderMid:"transparent"),color:viewFilter===f.id?C.cream:C.muted,borderRadius:7,padding:"5px 12px",cursor:"pointer",fontFamily:F.body,fontSize:12,fontWeight:600,transition:"all .15s"}}>{f.label}</button>)}</div>
        <Btn t={C} primary onClick={()=>{setEditing({...blank,category:catNames[0]||"Other"});setIsNew(true);}}>+ Add Item</Btn>
        <button onClick={()=>{setSelectMode(p=>!p);if(selectMode)setSelected(new Set());}} style={{background:selectMode?C.surface:"rgba(255,255,255,.03)",border:"1px solid "+(selectMode?C.red:C.border),color:selectMode?C.cream:C.muted,borderRadius:8,padding:"7px 14px",cursor:"pointer",fontFamily:F.body,fontSize:12,fontWeight:700,transition:"all .15s"}}>{selectMode?"\u2717 Cancel":"\u2610 Select"}</button>
        {selectMode&&selected.size>0&&<button onClick={()=>setConfirmBulkDel(true)} disabled={saving._bulk} style={{background:C.red,border:"none",color:C.cream,borderRadius:8,padding:"7px 14px",cursor:saving._bulk?"wait":"pointer",fontFamily:F.body,fontSize:12,fontWeight:700,opacity:saving._bulk?.5:1}}>Delete Selected ({selected.size})</button>}
      </div>
      {/* Mobile: card layout */}
      {isMobile?(<div style={{display:"flex",flexDirection:"column",gap:8}}>
        {selectMode&&<div style={{display:"flex",alignItems:"center",gap:8,padding:"8px 4px"}}><input type="checkbox" checked={displayed.length>0&&displayed.every(i=>selected.has(i.id))} onChange={toggleSelectAll} style={{width:18,height:18,accentColor:C.red,cursor:"pointer"}}/><span style={{fontSize:13,color:C.muted}}>Select All</span></div>}
        {displayed.length===0?<div style={{background:C.card,border:"1px solid "+C.border,borderRadius:14,padding:"40px",textAlign:"center",color:C.muted}}>No items found</div>
        :displayed.map(item=>{const isOn=item.showOnKiosk!==false;return(
          <div key={item.id} onClick={()=>{if(selectMode){toggleSelect(item.id);}else{setEditing({...item,price:String(item.price),showOnKiosk:item.showOnKiosk!==false});setIsNew(false);}}} style={{background:selected.has(item.id)?"rgba(155,28,28,.08)":C.card,border:"1px solid "+(selected.has(item.id)?C.red:C.border),borderRadius:12,padding:"14px 16px",display:"flex",alignItems:"center",gap:12,cursor:"pointer",transition:"background .15s",opacity:isOn?1:.6}}>
            {selectMode&&<input type="checkbox" checked={selected.has(item.id)} onChange={()=>toggleSelect(item.id)} onClick={e=>e.stopPropagation()} style={{width:18,height:18,accentColor:C.red,cursor:"pointer",flexShrink:0}}/>}
            <Img src={item.image} alt={item.name} style={{width:44,height:44,objectFit:"cover",borderRadius:7,border:"1px solid "+C.border,flexShrink:0}}/>
            <div style={{flex:1,minWidth:0}}>
              <div style={{fontSize:14,color:C.cream,fontWeight:600,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{item.name}{item.isBundle&&<span style={{background:"#1e40af",color:"#fff",fontSize:9,fontWeight:700,padding:"2px 6px",borderRadius:4,marginLeft:6,letterSpacing:1,verticalAlign:"middle"}}>BUNDLE</span>}{item.qbItemId&&<span style={{background:"#0b5e2b",color:"#7ee8a8",fontSize:9,fontWeight:700,padding:"2px 6px",borderRadius:4,marginLeft:6,letterSpacing:1,verticalAlign:"middle"}}>QB</span>}</div>
              <div style={{display:"flex",alignItems:"center",gap:8,marginTop:4}}>
                <span style={{fontFamily:F.display,fontSize:15,color:C.red,fontWeight:700}}>${(item.price||0).toFixed(2)}</span>
                <span style={{background:C.surface,border:"1px solid "+C.border,borderRadius:5,padding:"2px 8px",fontSize:10,color:C.muted}}>{item.category}</span>
              </div>
            </div>
            <div style={{display:"flex",alignItems:"center",gap:8,flexShrink:0}}>
              <span style={{width:8,height:8,borderRadius:"50%",background:isOn?C.greenText:C.muted,display:"inline-block"}}/>
              <span style={{color:C.muted,fontSize:18}}>{"\u203A"}</span>
            </div>
          </div>);})}
      </div>):(
      /* Desktop: full table */
      <div style={{background:C.card,border:"1px solid "+C.border,borderRadius:14,overflow:"hidden"}}><div style={{overflowX:"auto"}}><div style={{minWidth:750}}>
        <div style={{display:"grid",gridTemplateColumns:(selectMode?"36px ":"")+"44px 60px 1fr 130px 90px 100px 140px",borderBottom:"1px solid "+C.border,padding:"9px 16px",alignItems:"center"}}>{selectMode&&<div style={{display:"flex",alignItems:"center",justifyContent:"center"}}><input type="checkbox" checked={displayed.length>0&&displayed.every(i=>selected.has(i.id))} onChange={toggleSelectAll} style={{width:16,height:16,accentColor:C.red,cursor:"pointer"}}/></div>}{["","Image","Name","Category","Price","Kiosk","Actions"].map(h=><div key={h||"order"} style={{fontSize:10,letterSpacing:2,textTransform:"uppercase",color:C.muted}}>{h}</div>)}</div>
        {displayed.length===0?<div style={{padding:"40px",textAlign:"center",color:C.muted}}>No items found</div>:displayed.map((item)=>{const isOn=item.showOnKiosk!==false;const isSavingThis=saving[item.id];const onIdx=onMenuSorted.indexOf(item);return(
          <div key={item.id} data-row className="row-hover" draggable={isOn&&!selectMode} onDragStart={e=>isOn&&!selectMode&&handleDragStart(e,onIdx)} onDragOver={e=>isOn&&!selectMode&&handleDragOver(e,onIdx)} onDrop={e=>isOn&&!selectMode&&handleDrop(e,onIdx)} onDragEnd={handleDragEnd} style={{display:"grid",gridTemplateColumns:(selectMode?"36px ":"")+"44px 60px 1fr 130px 90px 100px 140px",borderBottom:"1px solid "+C.border,padding:"10px 16px",alignItems:"center",transition:"background .15s",opacity:isOn?1:.6,background:selected.has(item.id)?"rgba(155,28,28,.08)":overIdx===onIdx&&dragIdx!==onIdx?"rgba(155,28,28,.15)":"transparent",borderTop:overIdx===onIdx&&dragIdx!==onIdx?"2px solid "+C.red:"2px solid transparent"}}>
            {selectMode&&<div style={{display:"flex",alignItems:"center",justifyContent:"center"}}><input type="checkbox" checked={selected.has(item.id)} onChange={()=>toggleSelect(item.id)} style={{width:16,height:16,accentColor:C.red,cursor:"pointer"}}/></div>}
            <div style={{display:"flex",alignItems:"center",justifyContent:"center",cursor:isOn&&!selectMode?"grab":"default",userSelect:"none"}}>{isOn&&!selectMode?<span style={{display:"flex",flexDirection:"column",alignItems:"center",gap:1,color:isSavingThis?C.border:C.muted}} title="Drag to reorder"><span style={{fontSize:8,lineHeight:1}}>{"\u25B4"}</span><span style={{fontSize:16,lineHeight:.85,letterSpacing:0}}>{"\u2261"}</span><span style={{fontSize:8,lineHeight:1}}>{"\u25BE"}</span></span>:<span style={{fontSize:10,color:C.border}}>{isOn&&selectMode?"":"\u2014"}</span>}</div>
            <Img src={item.image} alt={item.name} style={{width:44,height:44,objectFit:"cover",borderRadius:7,border:"1px solid "+C.border}}/>
            <div><div style={{fontSize:14,color:C.cream,fontWeight:600}}>{item.name}{item.isBundle&&<span style={{background:"#1e40af",color:"#fff",fontSize:9,fontWeight:700,padding:"2px 6px",borderRadius:4,marginLeft:8,letterSpacing:1,verticalAlign:"middle"}}>BUNDLE</span>}{item.qbItemId&&<span style={{background:"#0b5e2b",color:"#7ee8a8",fontSize:9,fontWeight:700,padding:"2px 6px",borderRadius:4,marginLeft:8,letterSpacing:1,verticalAlign:"middle"}}>QB</span>}</div><div style={{fontSize:12,color:C.muted,marginTop:2,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",maxWidth:220}}>{item.description}</div></div>
            <div><span style={{background:C.surface,border:"1px solid "+C.border,borderRadius:5,padding:"3px 9px",fontSize:11,color:C.muted,whiteSpace:"nowrap"}}>{item.category}</span></div>
            <div style={{fontFamily:F.display,fontSize:15,color:C.red,fontWeight:700}}>${(item.price||0).toFixed(2)}</div>
            <div><button onClick={()=>toggleKiosk(item)} disabled={isSavingThis} style={{background:isOn?C.green:C.surface,color:isOn?C.greenText:C.muted,border:"1px solid "+(isOn?"rgba(74,222,128,.3)":C.border),borderRadius:20,padding:"6px 14px",cursor:isSavingThis?"wait":"pointer",fontFamily:F.body,fontSize:12,fontWeight:700,transition:"all .2s",opacity:isSavingThis?.5:1,minWidth:80,textAlign:"center"}}>{isSavingThis?"\u2026":isOn?"\u25CF On":"\u25CB Off"}</button></div>
            <div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button onClick={()=>{setEditing({...item,price:String(item.price),showOnKiosk:item.showOnKiosk!==false});setIsNew(false);}} style={smallBtn(false,false,C)}>Edit</button><button onClick={()=>setConfirmDel(item.id)} style={smallBtn(true,false,C)}>Del</button></div>
          </div>);})}
      </div></div></div>)}
      {editing&&<ItemModal item={editing} isNew={isNew} saving={saving._save} catNames={catNames} menu={menu} onChange={p=>setEditing(prev=>({...prev,...p}))} onSave={()=>saveItem(editing)} onClose={()=>setEditing(null)}/>}
      {confirmDel&&<ConfirmModal t={C}message={"Delete \""+((menu.find(m=>m.id===confirmDel)||{}).name||"")+"\"? This cannot be undone."} confirmLabel="Delete Item" danger onConfirm={()=>deleteItem(confirmDel)} onClose={()=>setConfirmDel(null)}/>}
      {confirmBulkDel&&<ConfirmModal t={C}message={"Delete "+selected.size+" selected item"+(selected.size!==1?"s":"")+"? This cannot be undone."} confirmLabel={"Delete "+selected.size+" Item"+(selected.size!==1?"s":"")} danger onConfirm={()=>{setConfirmBulkDel(false);deleteSelected();}} onClose={()=>setConfirmBulkDel(false)}/>}
    </div>
  );
}

function ItemModal({item,isNew,saving,catNames,onChange,onSave,onClose,menu}){const{T:C,TF:F}=useAdminTheme();const isQB=!!item.qbItemId;const{w:modalW}=useWindowSize();const modalMobile=modalW<768;
  const invalid=!item.name.trim()||!item.price||isNaN(parseFloat(item.price));const nonBundleItems=(menu||[]).filter(m=>!m.isBundle&&m.id!==item.id);const bundleItems=item.bundleItems||[];
  const [uploading,setUploading]=useState(false);const [uploadingBarcode,setUploadingBarcode]=useState(false);
  function addBundleItem(){onChange({bundleItems:[...bundleItems,{itemId:nonBundleItems[0]?.id||"",quantity:1}]});}
  function updateBundleItem(idx,field,val){const updated=[...bundleItems];updated[idx]={...updated[idx],[field]:val};onChange({bundleItems:updated});}
  function removeBundleItem(idx){onChange({bundleItems:bundleItems.filter((_,i)=>i!==idx)});}
  async function handlePhotoUpload(e){const file=e.target.files?.[0];if(!file)return;setUploading(true);try{const path="menu-images/"+Date.now()+"_"+file.name;const storageRef=ref(storage,path);await uploadBytes(storageRef,file);const url=await getDownloadURL(storageRef);onChange({image:url});}catch(err){console.error(err);}finally{setUploading(false);}}
  async function handleBarcodeUpload(e){const file=e.target.files?.[0];if(!file)return;setUploadingBarcode(true);try{const path="barcode-images/"+Date.now()+"_"+file.name;const storageRef=ref(storage,path);await uploadBytes(storageRef,file);const url=await getDownloadURL(storageRef);onChange({barcodeImage:url});}catch(err){console.error(err);}finally{setUploadingBarcode(false);}}
  const readOnlySt={...inputSt(false,C),opacity:0.6,cursor:"not-allowed",background:C.surface};
  return(<Modal t={C} title={isNew?"Add Menu Item":"Edit Menu Item"} onClose={onClose} wide>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14,marginBottom:14}}><Field t={C} label="Item Name *"><input value={item.name} onChange={isQB?undefined:e=>onChange({name:e.target.value})} readOnly={isQB} placeholder="e.g. Ribeye Steak" style={isQB?readOnlySt:inputSt(false,C)}/></Field><Field t={C} label="Price ($) *"><input value={item.price} onChange={isQB?undefined:e=>onChange({price:e.target.value})} readOnly={isQB} placeholder="0.00" type="number" step="0.01" style={isQB?readOnlySt:inputSt(false,C)}/></Field></div>
    <Field t={C} label="Description" style={{marginBottom:14}}><textarea value={item.description||""} onChange={e=>onChange({description:e.target.value})} rows={3} placeholder="Brief description" style={{...inputSt(false,C),resize:"vertical"}}/></Field>
    {modalMobile&&isQB?<Field t={C} label="SKU" style={{marginBottom:14}}><input value={item.sku||""} readOnly placeholder="e.g. RIB-001, GB-5LB" style={readOnlySt}/></Field>
    :<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:14,marginBottom:14}}><Field t={C} label="Category"><select value={item.category} onChange={e=>onChange({category:e.target.value})} style={inputSt(true,C)}>{(catNames||[]).map(c=><option key={c} value={c}>{c}</option>)}</select></Field><Field t={C} label="SKU"><input value={item.sku||""} onChange={isQB?undefined:e=>onChange({sku:e.target.value})} readOnly={isQB} placeholder="e.g. RIB-001, GB-5LB" style={isQB?readOnlySt:inputSt(false,C)}/></Field><Field t={C} label="Stock Qty"><input value={item.stock===null||item.stock===undefined?"":item.stock} onChange={isQB?undefined:e=>onChange({stock:e.target.value})} readOnly={isQB} placeholder="Leave blank = unlimited" type="number" min="0" style={isQB?readOnlySt:inputSt(false,C)}/></Field></div>}
    {isQB?(item.image?<Field t={C} label="Product Photo (from QuickBooks)" style={{marginBottom:14}}><div style={{marginTop:6}}><Img src={item.image} alt="preview" style={{height:110,width:"100%",objectFit:"cover",borderRadius:10,border:"1px solid "+C.border}}/></div></Field>:!modalMobile&&<div style={{fontSize:12,color:C.muted,marginBottom:14,padding:"10px 14px",background:C.surface,borderRadius:10,border:"1px solid "+C.border}}>No photo found in QuickBooks. Add one in QB and re-sync.</div>):<><Field t={C} label="Product Photo" style={{marginBottom:14}}>
      <div style={{display:"flex",gap:10,alignItems:"center"}}>
        <label style={{background:C.surface,border:"1px solid "+C.border,borderRadius:10,padding:"10px 16px",cursor:"pointer",fontFamily:F.body,fontSize:13,color:C.muted,fontWeight:600,whiteSpace:"nowrap"}}>{uploading?"Uploading\u2026":"Upload Photo"}<input type="file" accept="image/*" onChange={handlePhotoUpload} style={{display:"none"}}/></label>
        <div style={{fontSize:12,color:C.muted}}>or</div>
        <input value={item.image||""} onChange={e=>onChange({image:e.target.value})} placeholder="Paste image URL…" style={{...inputSt(false,C),flex:1}}/>
      </div>
    </Field>
    {item.image&&<div style={{marginBottom:14}}><Img src={item.image} alt="preview" style={{height:110,width:"100%",objectFit:"cover",borderRadius:10,border:"1px solid "+C.border}}/></div>}</>}
    <Field t={C} label="Barcode Image" style={{marginBottom:14}}>
      <div style={{display:"flex",gap:10,alignItems:"center"}}>
        <label style={{background:C.surface,border:"1px solid "+C.border,borderRadius:10,padding:"10px 16px",cursor:"pointer",fontFamily:F.body,fontSize:13,color:C.muted,fontWeight:600,whiteSpace:"nowrap"}}>{uploadingBarcode?"Uploading\u2026":"Upload Barcode"}<input type="file" accept="image/*" onChange={handleBarcodeUpload} style={{display:"none"}}/></label>
        {item.barcodeImage&&<button onClick={()=>onChange({barcodeImage:""})} style={{background:C.errorBg,border:"none",color:C.errorText,borderRadius:7,padding:"6px 12px",cursor:"pointer",fontSize:12,fontWeight:600}}>Remove</button>}
      </div>
    </Field>
    {item.barcodeImage&&<div style={{marginBottom:14,background:"#fff",borderRadius:10,padding:"10px",display:"flex",justifyContent:"center"}}><img src={item.barcodeImage} alt="barcode" style={{maxHeight:80,objectFit:"contain"}}/></div>}
    <Field t={C} label="Show on Kiosk" style={{marginBottom:14}}><button onClick={()=>onChange({showOnKiosk:!item.showOnKiosk})} style={{width:"100%",background:item.showOnKiosk?"rgba(22,101,52,.2)":"rgba(255,255,255,.03)",color:item.showOnKiosk?C.greenText:C.muted,border:"1px solid "+(item.showOnKiosk?"rgba(74,222,128,.3)":C.border),borderRadius:10,padding:"10px 13px",cursor:"pointer",fontFamily:F.body,fontSize:13,fontWeight:700,textAlign:"left",transition:"all .2s"}}>{item.showOnKiosk?"\u25CF Visible on kiosk":"\u25CB Hidden from kiosk"}</button></Field>
    {!modalMobile&&<><Field t={C} label="Bundle" style={{marginBottom:14}}><button onClick={()=>onChange({isBundle:!item.isBundle,bundleItems:item.isBundle?[]:(item.bundleItems||[])})} style={{width:"100%",background:item.isBundle?"#1e40af":C.surface,color:item.isBundle?C.cream:C.muted,border:"1px solid "+(item.isBundle?"#3b82f6":C.border),borderRadius:10,padding:"10px 13px",cursor:"pointer",fontFamily:F.body,fontSize:13,fontWeight:700,textAlign:"left",transition:"all .2s"}}>{item.isBundle?"\u25C6 This is a Bundle":"\u25CB Regular item \u2014 click to make a bundle"}</button></Field>
    {item.isBundle&&<Field t={C} label="Bundle Contents" style={{marginBottom:14}}><div style={{background:C.card,border:"1px solid "+C.border,borderRadius:10,padding:12}}>{bundleItems.length===0&&<div style={{fontSize:12,color:C.muted,padding:"8px 0",textAlign:"center"}}>No items added yet</div>}{bundleItems.map((bi,idx)=><div key={idx} style={{display:"flex",gap:8,alignItems:"center",marginBottom:8}}><select value={bi.itemId} onChange={e=>updateBundleItem(idx,"itemId",e.target.value)} style={{...inputSt(true),flex:1}}><option value="">Select item\u2026</option>{nonBundleItems.map(m=><option key={m.id} value={m.id}>{m.name} (${(m.price||0).toFixed(2)})</option>)}</select><div style={{display:"flex",alignItems:"center",gap:4}}><span style={{fontSize:11,color:C.muted}}>Qty:</span><input type="number" min="1" max="99" value={bi.quantity} onChange={e=>updateBundleItem(idx,"quantity",Math.max(1,parseInt(e.target.value)||1))} style={{...inputSt(false,C),width:55,textAlign:"center"}}/></div><button onClick={()=>removeBundleItem(idx)} style={{background:C.errorBg,border:"none",color:C.errorText,cursor:"pointer",fontSize:14,width:32,height:32,borderRadius:7,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>{"\u2715"}</button></div>)}<button onClick={addBundleItem} disabled={nonBundleItems.length===0} style={{background:C.surface,border:"1px dashed "+C.border,color:C.muted,borderRadius:8,padding:"8px 14px",cursor:"pointer",fontSize:12,fontWeight:600,width:"100%",marginTop:4}}>+ Add Item to Bundle</button></div>{bundleItems.length>0&&<div style={{fontSize:11,color:C.muted,marginTop:6}}>Items value: ${bundleItems.reduce((sum,bi)=>{const m=nonBundleItems.find(x=>x.id===bi.itemId);return sum+(m?(m.price||0)*bi.quantity:0);},0).toFixed(2)} {"\u2014"} Bundle price: ${parseFloat(item.price||0).toFixed(2)}</div>}</Field>}</>}
    <div style={{display:"flex",justifyContent:"flex-end",gap:10}}><Btn t={C} ghost onClick={onClose}>Cancel</Btn><Btn t={C} primary onClick={onSave} disabled={invalid||saving||uploading||uploadingBarcode}>{saving?"Saving\u2026":isNew?"Add Item":"Save Changes"}</Btn></div>
  </Modal>);
}
